### ISSUE TITLE
Google Search rolled different UI and the search button does not worked

### ISSUE THREAD

**Issue by dnet890** [tadwohlrapp/reddit-search-on-google#2]
Hello
Google load different UI and the search button is gone
![image](https://user-images.githubusercontent.com/29157187/218686989-ffd875ec-7ac4-4fe2-9e28-4dc37f68aaaa.png)

**Comment by tadwohlrapp** [comment]
Thank you for letting me know and sorry for taking so long to reply to you!

I finally had access to the redesigned Google Search page today and updated the extension accordingly:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/2788192/232825240-1a902641-05ac-4a04-a3f7-d2484478972c.png">

The new version 0.3.0 has just been submitted to all three web stores and should be available within the coming days.
